CREATE TABLE `t_produto` (
  `CD_PRODUTO` int NOT NULL AUTO_INCREMENT,
  `NM_PRODUTO` varchar(60) NOT NULL,
  `VL_PRODUTO` decimal(9,2) NOT NULL,
  `DT_VALIDADE` date NOT NULL,
  PRIMARY KEY (`CD_PRODUTO`)
);
CREATE PROCEDURE `PR_INSERT_PRODUTO`(
	IN P_NM_PRODUTO VARCHAR(255),
    IN P_VL_PRODUTO DECIMAL(9, 2),
    IN P_DT_VALIDADE DATE
)
BEGIN
	INSERT INTO T_PRODUTO (NM_PRODUTO, VL_PRODUTO, DT_VALIDADE) VALUES (P_NM_PRODUTO, P_VL_PRODUTO, P_DT_VALIDADE);
END;